### ISSUE TITLE
[BUG] docker-compose mlflow, minio network error

### ISSUE THREAD

**Issue by SSunQ** [gume-gume/MLOps-project#102]
### ✔코드경로(line 포함)

docker-compose로 연결하기 위해 코드를 밑에처럼 만들어 놨습니다.

Minio 
```
s3:
    image:  quay.io/minio/minio
    restart: unless-stopped
    command: minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_volume:/data
    networks:
      default_bridge:
        ipv4_address: 172.26.0.6
```
Mlflow
```
mlflow:
    container_name: tracker_mlflow
    image: gumegume/mlflow:1.1.0
    restart: always
    ports:
      - 5000:5000
    networks:
      default_bridge:
        ipv4_address: 172.26.0.9
    environment:
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_ACCESS_KEY_ID=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://172.26.0.6:9000
    depends_on:
      - s3
      - db
    command: mlflow server --backend-store-uri postgresql://postgres:postgres@172.26.0.7/income_db --default-artifact-root s3://mlflow --host 0.0.0.0
```

### ✔ 오류메시지

오류메시지는 나오는 것이없고 API에서 train을 시켰을 때 훈련이 잘 되고 db에 저장은 잘 됩니다. 하지만 모델이 minio에 저장을 하지 못합니다 
환경변수에 문제가 있나 하고 
MLFLOW_S3_ENDPOINT_URL=http://172.26.0.6:9000 를 MLFLOW_S3_ENDPOINT_URL=http://127:0.0.1:9000 등 할 수 있는건 다 해본거 같습니다.

### ✔ 버전정보
python 3.9.7

### ✔ 버그에 대한 뇌피셜

환경변수나 포트 연결을 할 때 문제가 있는 것 같습니다
